name: "minecraft-locations"
services:
  postgres:
    image: postgres:17
    ports:
      - "5421:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minecraft-locations
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./docker-pg-init.sql:/docker-entrypoint-initdb.d/docker-pg-init.sql"
    logging:
      driver: none
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'minecraft-locations']
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  app_network:
    driver: bridge
volumes:
  postgres_data:
